name: R-CMD-check

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Debug renv cache contents before restore
        run: |
          ls -la renv/library
      
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: |
            ./renv/library
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Set up R dependencies with renv
        run: |
          Rscript -e 'install.packages("renv", repos = "https://cloud.r-project.org")'
          Rscript -e 'renv::restore()'


      - name: Debug renv cache contents after restore
        run: |
          ls -la renv/library
      - name: Run tests
        working-directory: ${{ github.workspace }}
        run: |
          Rscript -e 'testthat::test_dir("R-scripts")'
