name: R-CMD-check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Set up R dependencies with renv
        run: |
          Rscript -e 'install.packages("renv", repos = "https://cran.csie.ntu.edu.tw/")'
          Rscript -e 'renv::restore()'

      - name: Run R script
        run: |
          Rscript R-scripts/utils.R

      - name: Run tests
        run: |
          Rscript -e 'testthat::test_dir("tests")'
